# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: false
pandoc: false
addons:
  apt:
    packages:
      - gfortran
      - g++
      - libcurl4-openssl-dev
      - libxml2-dev
      - libssl-dev
r_binary_packages:
  - reshape2
  - dplyr
  - forcats
  - readr
  - shiny
  - ggplot2
  - stringr
  - tibble
  - tidyr
  - shinyWidgets
  - data.table
  - openxlsx
  - readxl
  - tidyverse
