# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
addons:
  apt:
    packages:
      - gfortran
      - g++
      - libcurl4-openssl-dev
      - libxml2-dev
      - libssl-dev
warnings_are_errors: false
